apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-backend
  namespace: kube-net
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-backend
  template:
    metadata:
      labels:
        app: kube-backend
    spec:
      containers:
        - name: backend
          image: nkwentihub/k8s-backend:latest
          imagePullPolicy: Always

          envFrom:
            - configMapRef:
                name: backend-config
          env:
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: JWT_SECRET
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: kube-backend
  namespace: kube-net
spec:
  type: ClusterIP
  ports:
    - port: 8080
  selector:
    app: kube-backend 