apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-frontend
  template:
    metadata:
      labels:
        app: kube-frontend
    spec:
      containers:
        - name: frontend
          image: ghcr.io/nkwenti-severian-ndongtsop/k8s-frontend:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: kube-frontend
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 30080
  selector:
    app: kube-frontend 