apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init
  namespace: kube-net
  labels:
    app: postgres
data:
  init.sql: |
    CREATE TABLE IF NOT EXISTS users (
        id SERIAL PRIMARY KEY,
        username VARCHAR(255) UNIQUE NOT NULL,
        password_hash VARCHAR(255) NOT NULL
    ); 