name: automated package push

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: k8s-backend
  IMAGE_PATH: nkwenti-severian-ndongtsop

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: login to container registry
        uses: docker/login-action@v2
        with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.PAT_TOKEN }}

      - name: Build project
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          push: true
          tags: |
            ghcr.io/${{ env.IMAGE_PATH }}/${{ env.IMAGE_NAME }}:latest
          